import { Check, Eye, X } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getDashboardData } from "@/server/dashboard/queries";
import { reviewDiscovery } from "@/server/actions/portfolio";

export default async function DiscoveriesPage({params}:PageProps<"/[locale]/discoveries">){const {locale}=await params;const context=await requireWorkspaceContext(locale);const [t,data]=await Promise.all([getTranslations("Discoveries"),getDashboardData(context.workspaceId)]);return <><PageHeader title={t("title")} subtitle={t("subtitle")}/><section className="panel"><div className="panel-body">{data.discoveries.map((item)=><article className="list-row" key={`${item.provider}-${item.project}`}><div className="row-main"><span className="provider-dot">{item.provider.slice(0,2).toUpperCase()}</span><div><strong>{item.provider} · {item.project}</strong><details><summary><Eye size={12}/>{t("evidence")}</summary><small>{item.evidence.join(" · ")}</small></details></div></div><div className="topbar-actions"><StatusBadge status="candidate" label={`${item.confidence}%`}/>{item.id.startsWith("demo-")?<span className="status-badge">Demo</span>:<><form action={reviewDiscovery}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="integrationId" value={item.id}/><input type="hidden" name="decision" value="ignore"/><button className="button button-small" type="submit"><X size={12}/>{t("ignore")}</button></form><form action={reviewDiscovery}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="integrationId" value={item.id}/><input type="hidden" name="decision" value="confirm"/><button className="button button-small button-primary" type="submit"><Check size={12}/>{t("confirm")}</button></form></>}</div></article>)}</div></section>{!data.discoveries.length&&<div className="empty">{t("empty")}</div>}</>}
