import { ActionForm } from "@/components/action-form";
import { Check, Eye, X } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getDiscoveryInbox } from "@/server/dashboard/discoveries";
import { Link } from "@/i18n/navigation";
import { reviewDiscovery } from "@/server/actions/portfolio";

export default async function DiscoveriesPage({params,searchParams}:PageProps<"/[locale]/discoveries">){const {locale}=await params;const context=await requireWorkspaceContext(locale);const query=await searchParams;const status=query.status==="ignored"||query.status==="confirmed"?query.status:"pending";const [t,data]=await Promise.all([getTranslations("Discoveries"),getDiscoveryInbox(context.workspaceId,Number(query.page??1),status)]);return <><PageHeader title={t("title")} subtitle={t("subtitle")}/><nav className="inbox-tabs" aria-label={t("filters")}>{(["pending","confirmed","ignored"] as const).map(value=><Link className="button" aria-current={status===value?"page":undefined} href={`/discoveries?status=${value}`} key={value}>{t(value)}</Link>)}</nav><section className="panel"><div className="panel-body">{data.discoveries.map((item)=><article className="list-row" key={item.id}><div className="row-main"><span className="provider-dot">{item.provider.slice(0,2).toUpperCase()}</span><div><strong>{item.provider} · {item.project}</strong><details><summary><Eye size={12}/>{t("evidence")}</summary><small>{item.evidence.join(" · ") || t("noEvidence")}</small></details></div></div><div className="topbar-actions"><StatusBadge status={status==="pending"?"candidate":status} label={`${item.confidence}%`}/>{item.id.startsWith("demo-")?<span className="status-badge">Demo</span>:<><ActionForm action={reviewDiscovery}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="integrationId" value={item.id}/><input type="hidden" name="decision" value="ignore"/><button className="button button-small" type="submit"><X size={12}/>{t("ignore")}</button></ActionForm><ActionForm action={reviewDiscovery}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="integrationId" value={item.id}/><input type="hidden" name="decision" value="confirm"/><button className="button button-small button-primary" type="submit"><Check size={12}/>{t("confirm")}</button></ActionForm></>}</div></article>)}</div></section><div className="list-pagination"><span>{t("count",{count:data.total})}</span>{data.page>1?<Link className="button" href={`/discoveries?status=${status}&page=${data.page-1}`}>{t("previous")}</Link>:null}{data.page<data.pageCount?<Link className="button" href={`/discoveries?status=${status}&page=${data.page+1}`}>{t("next")}</Link>:null}</div>{!data.discoveries.length&&<div className="empty">{t("empty")}</div>}</>}
