export const demoData = {
  metrics: { monthToDate: 8742n, monthlyCommitment: 12400n, forecast: 15630n, potentialWaste: 2900n, annualized: 148800n },
  categories: [{ name:"Infrastructure", amount:8200n, share:82 }, { name:"AI", amount:5100n, share:51 }, { name:"Development", amount:3200n, share:32 }, { name:"Email", amount:2000n, share:20 }],
  discoveries: [{ id:"demo-resend", provider:"Resend", project:"Parigo Website", confidence:95, age:"2h", evidence:["package.json → resend", ".env.example → RESEND_API_KEY", "src/email.ts → import resend"] }, { id:"demo-openai", provider:"OpenAI", project:"Jobio API", confidence:85, age:"1d", evidence:["package.json → openai", ".env.example → OPENAI_API_KEY"] }],
  alerts: [{ title:"SendGrid", detail:"Not detected for 24 days", amount:1900n }, { title:"Old Vercel team", detail:"No attached active project", amount:2000n }],
  projects: [{ id:"parigo", name:"Parigo Website", client:"Parigo", repositories:2, services:6, monthly:4700n, scan:"2h" }, { id:"jobio", name:"Jobio", client:"Internal", repositories:2, services:5, monthly:3900n, scan:"1d" }, { id:"spend", name:"Spend", client:"Internal", repositories:1, services:7, monthly:2700n, scan:"4h" }],
  clients: [{ id:"internal", name:"Internal", description:"YoDev products and internal operations", projects:3 }, { id:"parigo", name:"Parigo", description:"Client delivery and infrastructure", projects:2 }, { id:"demo", name:"Demo Client", description:"Development demonstration data", projects:1 }],
  services: [{ slug:"vercel", name:"Vercel", category:"hosting", projects:5, monthly:4000n, status:"active", last:"2h" }, { slug:"resend", name:"Resend", category:"email", projects:3, monthly:2000n, status:"confirmed", last:"2h" }, { slug:"openai", name:"OpenAI", category:"ai", projects:2, monthly:5100n, status:"candidate", last:"1d" }, { slug:"sendgrid", name:"SendGrid", category:"email", projects:0, monthly:1900n, status:"stale", last:"24d" }, { slug:"supabase", name:"Supabase", category:"database", projects:3, monthly:2500n, status:"active", last:"2h" }],
  billing: [{ id:"vercel", name:"YoDev Vercel", provider:"Vercel", owner:"YoDev", recurring:2000n, renewal:"—" }, { id:"resend", name:"YoDev Email", provider:"Resend", owner:"Shared", recurring:2000n, renewal:"Sep 1" }, { id:"sendgrid", name:"Legacy SendGrid", provider:"SendGrid", owner:"YoDev", recurring:1900n, renewal:"Aug 28" }, { id:"openai", name:"OpenAI Platform", provider:"OpenAI", owner:"YoDev", recurring:5100n, renewal:"Usage" }],
};
