import "server-only";

import { and, desc, eq, gte, inArray, lt, sql } from "drizzle-orm";
import { alerts, billingAccounts, clients, costEntries, detectionEvidence, projectIntegrations, projects, providers, repositories, subscriptions } from "@/db/schema";
import { requireDb } from "@/db";
import { env } from "@/lib/env";
import { normalizeMonthly } from "@/server/billing/money";
import { demoData } from "./demo";

export async function getDashboardData(workspaceId: string) {
  if (env.AUTH_TEST_MODE === "true" || !process.env.DATABASE_URL) return demoData;
  const db = requireDb();
  const now = new Date(); const monthStart = new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)); const monthEnd = new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));
  const [subscriptionRows,costRows,openAlerts,recentIntegrations,projectRows] = await Promise.all([
    db.select().from(subscriptions).where(and(eq(subscriptions.workspaceId, workspaceId),eq(subscriptions.status,"active"))),
    db.select().from(costEntries).where(and(eq(costEntries.workspaceId,workspaceId),gte(costEntries.periodEnd,monthStart),lt(costEntries.periodStart,monthEnd))),
    db.select({ id:alerts.id,title:alerts.title,description:alerts.description,billingAccountId:alerts.billingAccountId }).from(alerts).where(and(eq(alerts.workspaceId,workspaceId),eq(alerts.status,"open"))).orderBy(desc(alerts.createdAt)).limit(6),
    db.select({ id:projectIntegrations.id,provider:providers.name,project:projects.name,confidence:projectIntegrations.confidence }).from(projectIntegrations).innerJoin(providers,eq(providers.id,projectIntegrations.providerId)).innerJoin(projects,eq(projects.id,projectIntegrations.projectId)).where(and(eq(projectIntegrations.workspaceId,workspaceId),eq(projectIntegrations.reviewStatus,"pending"))).orderBy(desc(projectIntegrations.firstDetectedAt)).limit(6),
    db.select({ id:projects.id,name:projects.name,client:clients.name,repositories:sql<number>`count(distinct ${repositories.id})::int`,services:sql<number>`count(distinct ${projectIntegrations.id})::int` }).from(projects).innerJoin(clients,eq(clients.id,projects.clientId)).leftJoin(repositories,eq(repositories.projectId,projects.id)).leftJoin(projectIntegrations,eq(projectIntegrations.projectId,projects.id)).where(and(eq(projects.workspaceId,workspaceId),eq(projects.status,"active"))).groupBy(projects.id,clients.name).limit(8),
  ]);
  const monthlyCommitment = subscriptionRows.filter((row)=>row.currency==="EUR").reduce((sum,row)=>sum+normalizeMonthly(row).amountMinor,0n);
  const monthToDate = costRows.filter((row)=>row.currency==="EUR").reduce((sum,row)=>sum+row.amountMinor,0n);
  const wasteAccounts = new Set(openAlerts.filter((item)=>item.billingAccountId).map((item)=>item.billingAccountId));
  const potentialWaste = subscriptionRows.filter((row)=>wasteAccounts.has(row.billingAccountId)).reduce((sum,row)=>sum+normalizeMonthly(row).amountMinor,0n);
  const evidenceRows=recentIntegrations.length?await db.select({integrationId:projectIntegrations.id,key:detectionEvidence.key,filePath:detectionEvidence.filePath}).from(projectIntegrations).innerJoin(projects,eq(projects.id,projectIntegrations.projectId)).innerJoin(repositories,eq(repositories.projectId,projects.id)).innerJoin(detectionEvidence,and(eq(detectionEvidence.repositoryId,repositories.id),eq(detectionEvidence.providerId,projectIntegrations.providerId))).where(inArray(projectIntegrations.id,recentIntegrations.map((item)=>item.id))).limit(40):[];
  return { ...demoData, metrics:{ monthToDate,monthlyCommitment,forecast:monthlyCommitment+monthToDate,potentialWaste,annualized:monthlyCommitment*12n }, discoveries:recentIntegrations.map((item)=>({...item,age:"recent",evidence:evidenceRows.filter((row)=>row.integrationId===item.id).map((row)=>`${row.filePath??"manual"} → ${row.key}`)})), alerts:openAlerts.map((item)=>({title:item.title,detail:item.description,amount:0n})), projects:projectRows.map((item)=>({...item,monthly:0n,scan:"—"})) };
}

export async function getPortfolioData(workspaceId: string) {
  if (env.AUTH_TEST_MODE === "true" || !process.env.DATABASE_URL) return demoData;
  const db=requireDb();
  const [clientRows,projectRows,serviceRows,accountRows,subscriptionRows] = await Promise.all([
    db.select({id:clients.id,name:clients.name,description:clients.description,projects:sql<number>`count(${projects.id})::int`}).from(clients).leftJoin(projects,eq(projects.clientId,clients.id)).where(eq(clients.workspaceId,workspaceId)).groupBy(clients.id).orderBy(clients.name),
    db.select({id:projects.id,name:projects.name,client:clients.name,repositories:sql<number>`count(distinct ${repositories.id})::int`,services:sql<number>`count(distinct ${projectIntegrations.id})::int`}).from(projects).innerJoin(clients,eq(clients.id,projects.clientId)).leftJoin(repositories,eq(repositories.projectId,projects.id)).leftJoin(projectIntegrations,eq(projectIntegrations.projectId,projects.id)).where(eq(projects.workspaceId,workspaceId)).groupBy(projects.id,clients.name).orderBy(projects.name),
    db.select({slug:providers.slug,name:providers.name,category:providers.category,projects:sql<number>`count(distinct ${projectIntegrations.projectId})::int`,status:sql<string>`min(${projectIntegrations.lifecycleStatus})`}).from(projectIntegrations).innerJoin(providers,eq(providers.id,projectIntegrations.providerId)).where(eq(projectIntegrations.workspaceId,workspaceId)).groupBy(providers.id).orderBy(providers.name),
    db.select({id:billingAccounts.id,name:billingAccounts.name,provider:providers.name,owner:billingAccounts.ownerType}).from(billingAccounts).innerJoin(providers,eq(providers.id,billingAccounts.providerId)).where(eq(billingAccounts.workspaceId,workspaceId)).orderBy(billingAccounts.name),
    db.select().from(subscriptions).where(and(eq(subscriptions.workspaceId,workspaceId),eq(subscriptions.status,"active"))),
  ]);
  return { ...demoData, clients:clientRows,projects:projectRows.map((row)=>({...row,monthly:0n,scan:"—"})),services:serviceRows.map((row)=>({...row,monthly:0n,last:"—"})),billing:accountRows.map((row)=>{const accountSubscriptions=subscriptionRows.filter((item)=>item.billingAccountId===row.id);return {...row,recurring:accountSubscriptions.filter((item)=>item.currency==="EUR").reduce((sum,item)=>sum+normalizeMonthly(item).amountMinor,0n),renewal:accountSubscriptions.map((item)=>item.renewalDate).filter((date):date is Date=>Boolean(date)).sort((a,b)=>a.getTime()-b.getTime())[0]?.toISOString().slice(0,10)??"—"};}) };
}

export async function getProjectDetail(workspaceId:string,projectId:string){if(env.AUTH_TEST_MODE==="true"||!process.env.DATABASE_URL){const project=demoData.projects.find((item)=>item.id===projectId)??demoData.projects[0];return {project:{...project,status:"active" as const},repositories:[{id:"demo-repository",fullName:`yodev/${project.id}`,defaultBranch:"main",lastScan:project.scan,scanEnabled:true}],services:demoData.services.slice(0,project.services)};}const db=requireDb();const [project]=await db.select({id:projects.id,name:projects.name,client:clients.name,status:projects.status,repositories:sql<number>`count(distinct ${repositories.id})::int`,services:sql<number>`count(distinct ${projectIntegrations.id})::int`}).from(projects).innerJoin(clients,eq(clients.id,projects.clientId)).leftJoin(repositories,eq(repositories.projectId,projects.id)).leftJoin(projectIntegrations,eq(projectIntegrations.projectId,projects.id)).where(and(eq(projects.workspaceId,workspaceId),eq(projects.id,projectId))).groupBy(projects.id,clients.name).limit(1);if(!project)return null;const [repositoryRows,serviceRows]=await Promise.all([db.select({id:repositories.id,fullName:repositories.fullName,defaultBranch:repositories.defaultBranch,lastScan:repositories.lastSuccessfulScanAt,scanEnabled:repositories.scanEnabled}).from(repositories).where(and(eq(repositories.workspaceId,workspaceId),eq(repositories.projectId,projectId))),db.select({slug:providers.slug,name:providers.name,category:providers.category,status:projectIntegrations.lifecycleStatus,monthly:sql<bigint>`0::bigint`,last:projectIntegrations.lastDetectedAt,projects:sql<number>`1`}).from(projectIntegrations).innerJoin(providers,eq(providers.id,projectIntegrations.providerId)).where(and(eq(projectIntegrations.workspaceId,workspaceId),eq(projectIntegrations.projectId,projectId)))]);return {project:{...project,monthly:0n,scan:"—"},repositories:repositoryRows.map((item)=>({...item,lastScan:item.lastScan?.toISOString()??"Never"})),services:serviceRows};}

export async function getClientDetail(workspaceId:string,clientId:string){if(env.AUTH_TEST_MODE==="true"||!process.env.DATABASE_URL){const client=demoData.clients.find((item)=>item.id===clientId)??demoData.clients[0];return {client:{...client,status:"active" as const},projects:demoData.projects.filter((item)=>item.client===client.name).map((item)=>({...item,status:"active" as const}))};}const db=requireDb();const [client]=await db.select().from(clients).where(and(eq(clients.workspaceId,workspaceId),eq(clients.id,clientId))).limit(1);if(!client)return null;const projectRows=await db.select({id:projects.id,name:projects.name,client:clients.name,repositories:sql<number>`count(distinct ${repositories.id})::int`,services:sql<number>`count(distinct ${projectIntegrations.id})::int`,status:projects.status}).from(projects).innerJoin(clients,eq(clients.id,projects.clientId)).leftJoin(repositories,eq(repositories.projectId,projects.id)).leftJoin(projectIntegrations,eq(projectIntegrations.projectId,projects.id)).where(and(eq(projects.workspaceId,workspaceId),eq(projects.clientId,clientId))).groupBy(projects.id,clients.name).orderBy(projects.name);return {client,projects:projectRows.map((row)=>({...row,monthly:0n,scan:"—"}))};}
