import "server-only";

import { and, eq, inArray } from "drizzle-orm";
import { alerts, detectionEvidence, githubInstallations, integrationEvents, projectIntegrations, providers, repositories, repositoryProviderObservations, scanRuns } from "@/db/schema";
import { requireDb } from "@/db";
import { alertDedupeKey } from "@/server/alerts/rules";
import { GitHubRepositoryAdapter } from "@/server/github/adapter";
import { DeterministicRepositoryScanner, evidenceSignature, safeErrorMessage, type ScanMode } from "@/server/scanner";
import { FINGERPRINT_VERSION } from "@/server/scanner/fingerprints/registry";
import { logEvent } from "@/server/logging";

export async function runRepositoryScan({workspaceId,repositoryId,mode="quick",trigger="manual",force=false,idempotencyKey}:{workspaceId:string;repositoryId:string;mode?:ScanMode;trigger?:"manual"|"scheduled"|"initial";force?:boolean;idempotencyKey?:string}) {
  logEvent("scan_started",{workspaceId,repositoryId,mode,trigger});
  const db=requireDb();
  const [repository]=await db.select({repository:repositories,installation:githubInstallations}).from(repositories).innerJoin(githubInstallations,eq(githubInstallations.id,repositories.githubInstallationId)).where(and(eq(repositories.id,repositoryId),eq(repositories.workspaceId,workspaceId),eq(repositories.scanEnabled,true))).limit(1);
  if(!repository) throw new Error("Repository not found, disabled, or disconnected.");
  const adapter=new GitHubRepositoryAdapter(repository.installation.installationId);
  const ref={owner:repository.repository.owner,name:repository.repository.name,defaultBranch:repository.repository.defaultBranch};
  const commitSha=await adapter.getDefaultBranchSha(ref);
  if(!force&&repository.repository.lastScannedCommitSha===commitSha){const [skipped]=await db.insert(scanRuns).values({workspaceId,repositoryId,type:mode,trigger,status:"skipped",commitSha,idempotencyKey,fingerprintVersion:FINGERPRINT_VERSION,completedAt:new Date(),warnings:["unchanged_commit"]}).returning();logEvent("repository_skipped",{workspaceId,repositoryId,reason:"unchanged_commit"});return skipped;}
  let scanRunId:string;
  try{const [run]=await db.insert(scanRuns).values({workspaceId,repositoryId,type:mode,trigger,status:"running",commitSha,idempotencyKey,fingerprintVersion:FINGERPRINT_VERSION,startedAt:new Date()}).returning({id:scanRuns.id});scanRunId=run.id;}catch{throw new Error("A scan is already running for this repository.");}
  try{
    const snapshot=await adapter.loadSnapshot(ref,mode); const result=await new DeterministicRepositoryScanner().scan(snapshot,mode); const detected=result.detections.filter((item)=>item.confidence>=60);
    const providerRows=detected.length?await db.select().from(providers).where(inArray(providers.slug,detected.map((item)=>item.providerSlug))):[]; const providerBySlug=new Map(providerRows.map((item)=>[item.slug,item])); const detectedProviderIds=new Set(providerRows.map((item)=>item.id)); const priorObservations=!result.partial?await db.select().from(repositoryProviderObservations).where(and(eq(repositoryProviderObservations.workspaceId,workspaceId),eq(repositoryProviderObservations.repositoryId,repositoryId))):[]; const now=new Date();
    await db.transaction(async(tx)=>{
      for(const detection of detected){const provider=providerBySlug.get(detection.providerSlug);if(!provider)continue;
        if(detection.evidence.length)await tx.insert(detectionEvidence).values(detection.evidence.map((item)=>({workspaceId,scanRunId,repositoryId,providerId:provider.id,type:item.type,key:item.key,filePath:item.filePath,metadata:item.metadata,weight:item.weight})));
        await tx.insert(repositoryProviderObservations).values({workspaceId,repositoryId,providerId:provider.id,confidence:detection.confidence,present:true,consecutiveAbsences:0,firstAbsentAt:null,lastDetectedAt:now,lastSuccessfulScanRunId:scanRunId}).onConflictDoUpdate({target:[repositoryProviderObservations.workspaceId,repositoryProviderObservations.repositoryId,repositoryProviderObservations.providerId],set:{confidence:detection.confidence,present:true,consecutiveAbsences:0,firstAbsentAt:null,lastDetectedAt:now,lastSuccessfulScanRunId:scanRunId,updatedAt:now}});
        const signature=evidenceSignature(detection.evidence); const [existing]=await tx.select().from(projectIntegrations).where(and(eq(projectIntegrations.workspaceId,workspaceId),eq(projectIntegrations.projectId,repository.repository.projectId),eq(projectIntegrations.providerId,provider.id))).limit(1);
        if(existing){const materiallyNew=existing.evidenceSignature!==signature&&detection.confidence>existing.confidence;await tx.update(projectIntegrations).set({confidence:Math.max(existing.confidence,detection.confidence),lastDetectedAt:now,evidenceSignature:signature,lifecycleStatus:existing.lifecycleStatus==="stale"?"candidate":existing.lifecycleStatus,reviewStatus:existing.reviewStatus==="ignored"&&materiallyNew?"pending":existing.reviewStatus,updatedAt:now}).where(eq(projectIntegrations.id,existing.id));}
        else{const [integration]=await tx.insert(projectIntegrations).values({workspaceId,projectId:repository.repository.projectId,providerId:provider.id,confidence:detection.confidence,lastDetectedAt:now,evidenceSignature:signature}).returning({id:projectIntegrations.id});await tx.insert(integrationEvents).values({workspaceId,integrationId:integration.id,eventType:"detected",metadata:{confidence:detection.confidence}});await tx.insert(alerts).values({workspaceId,type:"NEW_PROVIDER_DETECTED",severity:"info",dedupeKey:alertDedupeKey("NEW_PROVIDER_DETECTED",[repository.repository.projectId,provider.id]),providerId:provider.id,projectId:repository.repository.projectId,title:`${provider.name} detected`,description:`New provider detected with ${detection.confidence}% confidence.`}).onConflictDoNothing();}
      }
      if(!result.partial){for(const observation of priorObservations.filter((item)=>!detectedProviderIds.has(item.providerId))){await tx.update(repositoryProviderObservations).set({present:false,consecutiveAbsences:observation.consecutiveAbsences+1,firstAbsentAt:observation.firstAbsentAt??now,lastSuccessfulScanRunId:scanRunId,updatedAt:now}).where(eq(repositoryProviderObservations.id,observation.id));}
        const integrations=await tx.select().from(projectIntegrations).where(and(eq(projectIntegrations.workspaceId,workspaceId),eq(projectIntegrations.projectId,repository.repository.projectId),inArray(projectIntegrations.lifecycleStatus,["active","candidate"])));
        for(const integration of integrations){const observations=await tx.select().from(repositoryProviderObservations).innerJoin(repositories,eq(repositories.id,repositoryProviderObservations.repositoryId)).where(and(eq(repositoryProviderObservations.workspaceId,workspaceId),eq(repositoryProviderObservations.providerId,integration.providerId),eq(repositories.projectId,repository.repository.projectId),eq(repositories.scanEnabled,true)));const absent=observations.length>0&&observations.every(({repository_provider_observations:item})=>!item.present&&item.consecutiveAbsences>=3&&Boolean(item.firstAbsentAt)&&now.getTime()-item.firstAbsentAt!.getTime()>=14*86400000);if(absent){await tx.update(projectIntegrations).set({lifecycleStatus:"stale",staleAt:now,updatedAt:now}).where(eq(projectIntegrations.id,integration.id));await tx.insert(integrationEvents).values({workspaceId,integrationId:integration.id,eventType:"stale",metadata:{reason:"three_complete_absences_over_fourteen_days"}});await tx.insert(alerts).values({workspaceId,type:"PROVIDER_STALE",severity:"warning",dedupeKey:alertDedupeKey("PROVIDER_STALE",[integration.id]),providerId:integration.providerId,projectId:integration.projectId,title:"Provider may be stale",description:"No evidence was found in three complete scans spanning at least fourteen days."}).onConflictDoNothing();}}
      }
      await tx.update(scanRuns).set({status:result.partial?"partial":"success",completedAt:now,filesInspected:result.filesInspected,bytesInspected:result.bytesInspected,evidenceCount:detected.reduce((sum,item)=>sum+item.evidence.length,0),warnings:result.warnings,updatedAt:now}).where(eq(scanRuns.id,scanRunId));
      await tx.update(repositories).set({lastKnownCommitSha:commitSha,lastScannedCommitSha:result.partial?repository.repository.lastScannedCommitSha:commitSha,lastSuccessfulScanAt:result.partial?repository.repository.lastSuccessfulScanAt:now,lastScanAttemptAt:now,updatedAt:now}).where(eq(repositories.id,repositoryId));
    });
    logEvent("scan_completed",{workspaceId,repositoryId,scanRunId,status:result.partial?"partial":"success",filesInspected:result.filesInspected,bytesInspected:result.bytesInspected,evidenceCount:detected.reduce((sum,item)=>sum+item.evidence.length,0)});return {id:scanRunId,status:result.partial?"partial":"success",detections:detected.length};
  }catch(error){const now=new Date();const message=safeErrorMessage(error);await db.transaction(async(tx)=>{await tx.update(scanRuns).set({status:"failed",completedAt:now,errorCode:"SCAN_FAILED",errorMessage:message,updatedAt:now}).where(eq(scanRuns.id,scanRunId));await tx.update(repositories).set({lastScanAttemptAt:now,updatedAt:now}).where(eq(repositories.id,repositoryId));await tx.insert(alerts).values({workspaceId,type:"SCAN_FAILED",severity:"warning",dedupeKey:alertDedupeKey("SCAN_FAILED",[repositoryId]),title:`Scan failed: ${repository.repository.fullName}`,description:message}).onConflictDoNothing();});logEvent("scan_failed",{workspaceId,repositoryId,scanRunId,errorCode:"SCAN_FAILED"});throw error;}
}
