export type LegalDocumentKey="legal"|"privacy"|"terms"|"dpa"|"subprocessors";
type Section={title:string;body:string};
export const legalCopy:Record<"fr"|"en",Record<LegalDocumentKey,Section[]>>={
  fr:{
    legal:[
      {title:"Éditeur et contact",body:"L’identité de l’éditeur et les coordonnées de contact figurent ci-dessous. Spend by YoDev est un service de suivi des fournisseurs et des dépenses techniques destiné aux professionnels."},
      {title:"Hébergement",body:"L’application est hébergée par Vercel et la base de données par Neon. La configuration actuellement auditée utilise la région Est des États-Unis. Aucune résidence exclusivement européenne des données n’est annoncée."},
      {title:"Propriété et contenus",body:"Vous conservez vos droits sur les informations de vos clients, projets et dépenses. L’accès à un dépôt ou à un compte fournisseur doit être autorisé par son titulaire. Le scanner analyse les fichiers en mémoire et conserve des indices structurés de détection, pas leur contenu."},
    ],
    privacy:[
      {title:"Données et finalités",body:"Spend traite les informations de compte et de session, les appartenances aux espaces, les clients et projets renseignés, les métadonnées de dépôts, les indices de fournisseurs et les informations de dépenses. Ces traitements servent à fournir le service, contrôler les accès, expliquer les calculs et traiter les incidents. Les données commerciales de l’éditeur servent à gérer la relation client et la facturation."},
      {title:"Connexions et secrets",body:"Les accès fournisseurs sont utilisés pour les fonctions explicitement connectées. Les secrets des connecteurs sont chiffrés et exclus des exports métier. La déconnexion supprime les secrets stockés ; la révocation chez le fournisseur peut également être nécessaire. Les contenus des fichiers de dépôt ne sont ni archivés ni journalisés."},
      {title:"Conservation et suppression",body:"Le propriétaire peut exporter les données puis demander la suppression de l’espace dans Paramètres → Données et suppression, après la fin de l’abonnement. Les connecteurs sont arrêtés dès la demande. L’espace reste consultable pendant trente jours, puis les données métier sont purgées. Les pièces de facturation de l’éditeur et preuves contractuelles sont conservées séparément selon la politique applicable. L’effacement des sauvegardes suit leur expiration ; une restauration doit réappliquer les demandes de suppression."},
      {title:"Vos demandes",body:"Les demandes d’accès, de rectification, d’opposition, de limitation, de portabilité ou d’effacement peuvent être adressées au contact ci-dessous. Les demandes relatives aux données saisies par une entreprise sont traitées avec le propriétaire de son espace. Une réclamation peut être adressée à la CNIL. Les bases légales et durées précises de chaque traitement doivent être validées dans le registre avant l’ouverture commerciale."},
      {title:"Cookies et transferts",body:"Les cookies de session assurent l’authentification et la protection des accès. Le choix de thème et de langue sert à l’affichage. Les fournisseurs et lieux de traitement sont indiqués dans la liste des sous-traitants ; les garanties des transferts internationaux doivent être documentées avant l’ouverture commerciale."},
    ],
    terms:[
      {title:"Périmètre du service",body:"Spend fournit un inventaire de fournisseurs, un suivi des dépenses et des aides à la revue. La disponibilité des informations dépend des permissions, des API et des justificatifs renseignés. Les estimations et observations partielles sont identifiées comme telles. Les montants de devises différentes restent distincts lorsqu’aucun taux exploitable n’est disponible."},
      {title:"Compte et responsabilités",body:"Le propriétaire gère les membres de son espace et les autorisations des comptes connectés. Chaque utilisateur doit protéger ses accès et utiliser le service pour des données qu’il est autorisé à traiter. Les corrections d’écritures manuelles conservent l’historique et exigent un motif ; les données importées d’un fournisseur doivent être corrigées à leur source."},
      {title:"Abonnement et renouvellement",body:"L’offre choisie, la périodicité, la devise et les taxes applicables sont présentées avant confirmation du paiement. L’abonnement se renouvelle selon la périodicité choisie. La gestion et la résiliation sont accessibles depuis les paramètres de facturation via le portail Stripe. L’accès payant dépend du statut confirmé par Stripe ; une demande de paiement ne vaut pas activation."},
      {title:"Fin de service et restitution",body:"La fin de l’abonnement arrête les connexions. La suppression des données métier fait l’objet d’une demande distincte du propriétaire, avec trente jours pour exporter les données et annuler la demande. L’annulation de la suppression ne rétablit pas les secrets révoqués. Les obligations de conservation de l’éditeur restent distinctes."},
      {title:"Assistance et engagements",body:"L’assistance est joignable aux coordonnées ci-dessous. Aucun délai de réponse garanti, taux de disponibilité contractuel, indemnité ou plafond de responsabilité n’est proposé dans ce brouillon. Ces conditions, ainsi que la fiscalité, le droit applicable et le règlement des litiges, doivent être finalisées avant la commercialisation."},
    ],
    dpa:[
      {title:"Objet et instructions",body:"Pour les données personnelles confiées dans l’espace client, le client détermine les finalités et instructions ; l’éditeur les traite pour fournir l’inventaire et le suivi des dépenses. Les traitements comprennent la collecte auprès des sources autorisées, l’organisation, la consultation, l’export et l’effacement. Les personnes concernées peuvent être les utilisateurs, collaborateurs, contacts clients et interlocuteurs fournisseurs."},
      {title:"Sécurité et confidentialité",body:"Les accès sont limités par espace et par rôle. Les secrets de connexion sont chiffrés, les montants sont conservés avec leur devise, les événements utiles à la traçabilité sont enregistrés sans contenu de dépôt ni secret. Les personnes habilitées doivent respecter la confidentialité. La procédure d’incident doit permettre d’informer le client sans délai indu après constat d’une violation et de documenter les mesures prises."},
      {title:"Assistance et sous-traitants",body:"L’éditeur assiste le client pour répondre aux demandes des personnes et documenter la sécurité, les incidents et les analyses d’impact nécessaires. La liste des prestataires, leurs rôles et leurs lieux de traitement figure dans le document Sous-traitants. Le mécanisme de notification des changements, le droit d’objection, les garanties des transferts et les modalités d’audit doivent être convenus dans le contrat final."},
      {title:"Restitution et fin de traitement",body:"L’export est disponible au propriétaire. Une demande de suppression arrête les connexions et ouvre une période d’export de trente jours avant purge des données métier. Les identités pouvant appartenir à plusieurs espaces sont traitées séparément, de même que les obligations légales propres à l’éditeur. Les copies de sauvegarde expirent selon une politique à valider ; toute restauration doit réappliquer les effacements."},
    ],
    subprocessors:[
      {title:"Vercel — application",body:"Exécution et livraison de l’application, requêtes HTTP et journaux techniques. Région applicative auditée : iad1, États-Unis. Entité contractante, sous-traitants ultérieurs, durées des journaux et garanties de transfert à confirmer sur le contrat du compte."},
      {title:"Neon — base de données",body:"Stockage PostgreSQL des comptes et données métier. Région auditée : aws-us-east-1, États-Unis. Historique de restauration observé : six heures. Les copies de répétition temporaires expirent séparément. La politique de sauvegarde commerciale reste à finaliser."},
      {title:"GitHub et Google — identité et sources",body:"GitHub permet l’authentification et l’accès aux dépôts explicitement autorisés. Google est une option d’authentification lorsqu’elle est configurée. Ces plateformes ont également leurs propres relations avec les utilisateurs ; leur qualification et leurs garanties doivent être précisées dans la documentation contractuelle."},
      {title:"Stripe et Resend — services à activer",body:"Stripe est prévu pour le paiement et le portail d’abonnement ; Resend pour les invitations transactionnelles. Leur configuration de staging n’est pas complète au moment de l’audit. L’activation nécessite de confirmer les entités contractantes, les domaines autorisés, les lieux de traitement et les garanties applicables."},
    ],
  },
  en:{
    legal:[
      {title:"Publisher and contact",body:"Publisher identity and contact details appear below. Spend by YoDev is a provider inventory and technical spending service for businesses."},
      {title:"Hosting",body:"Vercel hosts the application and Neon hosts PostgreSQL. The audited deployment uses the eastern United States. Exclusive European data residency is not advertised."},
      {title:"Content ownership",body:"You retain your rights to client, project and spending information. Repository and provider access must be authorized by their owners. The scanner processes file contents in memory and retains structured detection evidence, not file contents."},
    ],
    privacy:[
      {title:"Data and purposes",body:"Spend processes account and session information, workspace memberships, client and project records, repository metadata, provider evidence and spending records to deliver the service, enforce access, explain calculations and handle incidents. Publisher billing records support the commercial relationship."},
      {title:"Connections and credentials",body:"Provider access serves explicitly connected features. Connector secrets are encrypted and excluded from business exports. Disconnecting removes stored credentials; revocation at the provider may also be needed. Repository file contents are not stored or logged."},
      {title:"Retention and deletion",body:"After ending the subscription, the owner can request deletion in Settings → Data and deletion. Connections stop immediately. The workspace remains readable for thirty days before business data is purged. Publisher invoices and contractual evidence are retained separately under the applicable policy. Backup erasure follows expiry; restoring a backup must reapply deletion requests."},
      {title:"Your requests",body:"Send access, correction, objection, restriction, portability or erasure requests to the contact below. Requests concerning a company's records are coordinated with its workspace owner. Complaints may be submitted to the CNIL. Specific legal bases and retention periods must be finalized in the processing register before commercial launch."},
      {title:"Cookies and transfers",body:"Session cookies support authentication and access protection. Theme and language preferences control presentation. Provider locations are listed in the subprocessors document; international transfer safeguards must be documented before commercial launch."},
    ],
    terms:[
      {title:"Service scope",body:"Spend provides provider inventory, spending tracking and review assistance. Available information depends on permissions, provider APIs and supplied records. Estimates and partial observations are identified. Different currencies remain separate when a usable exchange rate is unavailable."},
      {title:"Accounts and responsibilities",body:"The owner manages members and connected account permissions. Users must protect their access and process only authorized data. Manual financial corrections retain history and require a reason. Provider records must be corrected at their source."},
      {title:"Subscriptions",body:"The selected plan, billing interval, currency and applicable taxes are displayed before payment confirmation. Subscriptions renew at the selected interval. Billing settings provide access to the Stripe portal for management and cancellation. Paid access requires a confirmed Stripe status; initiating payment does not activate it."},
      {title:"Ending the service",body:"Subscription termination stops connections. Business data deletion requires a separate owner request, with thirty days to export or cancel deletion. Cancelling deletion does not restore revoked secrets. The publisher's record retention obligations remain separate."},
      {title:"Support and commitments",body:"Contact support using the details below. This draft does not offer a guaranteed response time, contractual uptime, compensation or liability cap. Those terms, taxation, governing law and dispute resolution must be finalized before commercial launch."},
    ],
    dpa:[
      {title:"Scope and instructions",body:"For personal data entrusted to a workspace, the client determines purposes and instructions; the publisher processes it to provide provider inventory and spending tracking. Operations include authorized collection, organization, access, export and erasure. Data subjects may include users, employees, client contacts and provider representatives."},
      {title:"Security and confidentiality",body:"Access is restricted by workspace and role. Connection secrets are encrypted, amounts retain their currency, and audit events exclude repository contents and secrets. Authorized personnel must maintain confidentiality. Incident procedures must support notifying the client without undue delay after discovering a breach and documenting remedial action."},
      {title:"Assistance and subprocessors",body:"The publisher assists with individual requests, security evidence, incidents and necessary impact assessments. Providers, roles and locations appear in the subprocessors document. Change notification, objection rights, transfer safeguards and audit procedures must be agreed in the final contract."},
      {title:"Return and erasure",body:"Owners can export data. A deletion request stops connections and opens a thirty-day export period before business data erasure. Identities shared across workspaces and the publisher's own legal obligations are handled separately. Backup retention must be finalized, and restored backups must reapply erasures."},
    ],
    subprocessors:[
      {title:"Vercel — application",body:"Application execution and delivery, HTTP requests and technical logs. Audited region: iad1, United States. Contracting entity, further processors, log retention and transfer safeguards require confirmation against the account contract."},
      {title:"Neon — database",body:"PostgreSQL storage for accounts and business records. Audited region: aws-us-east-1, United States. Observed restore history: six hours. Temporary rehearsal copies expire separately. The commercial backup policy remains to be finalized."},
      {title:"GitHub and Google — identity and sources",body:"GitHub provides sign-in and explicitly authorized repository access. Google sign-in is optional when configured. These platforms also have their own user relationships; their legal roles and safeguards must be specified in the contractual documentation."},
      {title:"Stripe and Resend — pending activation",body:"Stripe is planned for payments and subscription management; Resend for transactional invitations. Staging configuration was incomplete at audit time. Activation requires confirmation of contracting entities, authorized domains, processing locations and applicable safeguards."},
    ],
  },
};
