import { Archive, GitBranch } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getProjectDetail } from "@/server/dashboard/queries";
import { scanRepositoryAction } from "@/server/actions/scans";
import { archiveProject } from "@/server/actions/portfolio";

export default async function ProjectDetailPage({params}:PageProps<"/[locale]/projects/[projectId]">){const {locale,projectId}=await params;const context=await requireWorkspaceContext(locale);const data=await getProjectDetail(context.workspaceId,projectId);const project=data?.project;return <><PageHeader title={project?.name??"Project"} subtitle={`${project?.client??""} · ${project?.repositories??0} repositories`} action={project&&project.status!=="archived"&&!project.id.startsWith("demo-")?<form action={archiveProject}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="projectId" value={projectId}/><button className="button" type="submit"><Archive size={13}/>Archive</button></form>:undefined}/><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Repositories</h2></div><div className="panel-body">{data?.repositories.map((repository)=><div className="list-row" key={repository.id}><div className="row-main"><span className="provider-dot"><GitBranch size={15}/></span><div><strong>{repository.fullName}</strong><small>{repository.defaultBranch} · last scan {repository.lastScan}</small></div></div><div className="topbar-actions"><StatusBadge status="active" label={repository.scanEnabled?"Enabled":"Disabled"}/>{repository.id==="demo-repository"?<span className="status-badge">Demo</span>:<form action={scanRepositoryAction}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="repositoryId" value={repository.id}/><input type="hidden" name="mode" value="quick"/><input type="hidden" name="force" value="true"/><button className="button button-small" type="submit">Scan now</button></form>}</div></div>)}</div></section><section className="panel"><div className="panel-head"><h2>Integrations</h2></div><div className="panel-body">{data?.services.map((service)=><div className="list-row" key={service.slug}><strong>{service.name}</strong><StatusBadge status={service.status as "active"|"confirmed"|"candidate"|"stale"}/></div>)}</div></section></div></>}
