import { ArrowRight, AlertTriangle } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { PageHeader } from "@/components/page-header";
import { Link } from "@/i18n/navigation";
import { formatMoney } from "@/lib/utils";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getDashboardData } from "@/server/dashboard/queries";

export default async function DashboardPage({params}:PageProps<"/[locale]/dashboard">){const {locale}=await params;const context=await requireWorkspaceContext(locale);const [t,data]=await Promise.all([getTranslations("Dashboard"),getDashboardData(context.workspaceId)]);const metrics=[[t("monthToDate"),data.metrics.monthToDate,"Actual"],[t("monthlyCommitment"),data.metrics.monthlyCommitment,"Recurring"],[t("forecast"),data.metrics.forecast,"Conservative"],[t("potentialWaste"),data.metrics.potentialWaste,"Advisory"],[t("annualized"),data.metrics.annualized,"Recurring × 12"]] as const;return <><PageHeader title={t("title")} subtitle={t("subtitle")}/><section className="metric-grid">{metrics.map(([label,value,note],index)=><article className={`metric-card ${index===3?"attention":""}`} key={label}><span>{label}</span><strong>{formatMoney(value,"EUR",locale)}</strong><small>{note}</small></article>)}</section><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>{t("byCategory")}</h2></div><div className="panel-body">{data.categories.map((item)=><div className="bar-row" key={item.name}><div className="bar-label"><span>{item.name}</span><strong>{formatMoney(item.amount,"EUR",locale)}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.min(item.share,100)}%`}}/></div></div>)}<p className="hint">{t("excludedCurrency")}</p></div></section><section className="panel"><div className="panel-head"><h2>{t("attention")}</h2><Link href="/discoveries">View <ArrowRight size={11}/></Link></div><div className="panel-body">{data.alerts.map((item)=><div className="list-row" key={`${item.title}-${item.detail}`}><div className="row-main"><span className="provider-dot"><AlertTriangle size={14}/></span><div><strong>{item.title}</strong><small>{item.detail}</small></div></div><div className="row-value">{item.amount?formatMoney(item.amount,"EUR",locale):"—"}</div></div>)}</div></section><section className="panel"><div className="panel-head"><h2>{t("recentDiscoveries")}</h2><Link href="/discoveries">View all</Link></div><div className="panel-body">{data.discoveries.map((item)=><div className="list-row" key={`${item.provider}-${item.project}`}><div className="row-main"><span className="provider-dot">{item.provider.slice(0,2).toUpperCase()}</span><div><strong>{item.provider}</strong><small>{item.project}</small></div></div><div className="row-value">{item.confidence}%<small>{item.age}</small></div></div>)}</div></section><section className="panel"><div className="panel-head"><h2>{t("projects")}</h2><Link href="/projects">View all</Link></div><div className="panel-body">{data.projects.map((item)=><div className="list-row" key={item.id}><div><strong>{item.name}</strong><small>{item.client} · {item.repositories} repos · {item.services} services</small></div><div className="row-value">{formatMoney(item.monthly,"EUR",locale)}<small>{item.scan}</small></div></div>)}</div></section></div></>}
