import { getTranslations } from "next-intl/server";
import { PageHeader } from "@/components/page-header";
import { formatMoney } from "@/lib/utils";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getPortfolioData } from "@/server/dashboard/queries";
import { BillingForms } from "@/components/billing-form";
import { archiveBillingAccount } from "@/server/actions/billing";
import { Link } from "@/i18n/navigation";
import { InvoiceForm } from "@/components/invoice-form";

export default async function SpendPage({params}:PageProps<"/[locale]/spend">){const {locale}=await params;const context=await requireWorkspaceContext(locale);const [t,data]=await Promise.all([getTranslations("Spend"),getPortfolioData(context.workspaceId)]);const labelKeys=["newAccount","newCost","name","provider","owner","workspace","client","shared","clientOwner","sharedProjects","sharedProjectsHelp","amountMinor","interval","month","year","account","costType","subscription","usage","credit","tax","manual","currency","periodStart","periodEnd","description","newInvoice","invoiceNumber","issuedAt","reconcileInvoice","allocationMethod","equal","manualAllocation","allocationBps","updateAllocation"] as const;const labels=Object.fromEntries(labelKeys.map((key)=>[key,t(key)])) as Record<(typeof labelKeys)[number],string>;const accounts=data.billing.map(({id,name,allocations})=>({id,name,allocations}));return <><PageHeader title={t("title")} subtitle={t("subtitle")} action={<Link className="button button-primary" href="/spend/optimizations">{t("optimizations")}</Link>}/>{data.unallocated?.length?<section className="panel" style={{marginBottom:16}}><div className="panel-head"><h2>{t("unallocated")}</h2></div><div className="panel-body">{data.unallocated.map((item)=><p key={item.currency}><strong>{formatMoney(item.amountMinor,item.currency,locale)}</strong> · {t("unallocatedHelp")}</p>)}</div></section>:null}<BillingForms locale={locale} accounts={accounts} clients={data.clients.map(({id,name})=>({id,name}))} projects={data.projects.map(({id,name})=>({id,name}))} labels={labels}/><InvoiceForm locale={locale} accounts={accounts} labels={labels}/><table className="data-table"><thead><tr><th>{t("account")}</th><th>{t("provider")}</th><th>{t("owner")}</th><th>{t("recurring")}</th><th>{t("renewal")}</th><th>{t("actions")}</th></tr></thead><tbody>{data.billing.map((item)=><tr key={item.id}><td data-label={t("account")}><strong>{item.name}</strong></td><td data-label={t("provider")}>{item.provider}</td><td data-label={t("owner")}>{item.owner}</td><td data-label={t("recurring")}>{formatMoney(item.recurring,"EUR",locale)}</td><td data-label={t("renewal")}>{item.renewal}</td><td data-label={t("actions")}>{item.id.startsWith("demo-")?"—":<form action={archiveBillingAccount}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="billingAccountId" value={item.id}/><button className="button button-small" type="submit">{t("archive")}</button></form>}</td></tr>)}</tbody></table></>}
