import { getTranslations } from "next-intl/server";
import { PageHeader } from "@/components/page-header";
import { formatMoney } from "@/lib/utils";
import { requireWorkspaceContext } from "@/server/auth/context";
import { getPortfolioData } from "@/server/dashboard/queries";
import { BillingForms } from "@/components/billing-form";
import { archiveBillingAccount } from "@/server/actions/billing";

export default async function SpendPage({params}:PageProps<"/[locale]/spend">){const {locale}=await params;const context=await requireWorkspaceContext(locale);const [t,data]=await Promise.all([getTranslations("Spend"),getPortfolioData(context.workspaceId)]);const labelKeys=["newAccount","newCost","name","provider","owner","workspace","client","shared","amountMinor","interval","month","year","account","costType","subscription","usage","credit","tax","manual","currency","periodStart","periodEnd","description"] as const;const labels=Object.fromEntries(labelKeys.map((key)=>[key,t(key)])) as Record<(typeof labelKeys)[number],string>;return <><PageHeader title={t("title")} subtitle={t("subtitle")}/><BillingForms locale={locale} accounts={data.billing.map(({id,name})=>({id,name}))} labels={labels}/><table className="data-table"><thead><tr><th>{t("account")}</th><th>{t("provider")}</th><th>{t("owner")}</th><th>{t("recurring")}</th><th>{t("renewal")}</th><th>{t("actions")}</th></tr></thead><tbody>{data.billing.map((item)=><tr key={item.id}><td data-label={t("account")}><strong>{item.name}</strong></td><td data-label={t("provider")}>{item.provider}</td><td data-label={t("owner")}>{item.owner}</td><td data-label={t("recurring")}>{formatMoney(item.recurring,"EUR",locale)}</td><td data-label={t("renewal")}>{item.renewal}</td><td data-label={t("actions")}>{item.id.startsWith("demo-")?"—":<form action={archiveBillingAccount}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="billingAccountId" value={item.id}/><button className="button button-small" type="submit">{t("archive")}</button></form>}</td></tr>)}</tbody></table></>}
