import "dotenv/config";
import { eq } from "drizzle-orm";
import { alerts, authMembers, authOrganizations, authUsers, billingAccountProjects, billingAccounts, clients, costEntries, projectIntegrations, projects, providers, repositories, subscriptions, workspaceProfiles } from "../src/db/schema";
import { requireDb } from "../src/db";
import { providerCatalog } from "../src/server/providers/catalog";

const ids={workspace:"00000000-0000-4000-8000-000000000001",internal:"00000000-0000-4000-8000-000000000011",parigo:"00000000-0000-4000-8000-000000000012",demo:"00000000-0000-4000-8000-000000000013",spend:"00000000-0000-4000-8000-000000000021",parigoWeb:"00000000-0000-4000-8000-000000000022",jobio:"00000000-0000-4000-8000-000000000023"};

async function main(){const db=requireDb();await db.transaction(async(tx)=>{
  await tx.insert(authUsers).values({id:"seed-owner",name:"Yoann",email:"owner@example.invalid",emailVerified:true,githubId:"seed"}).onConflictDoNothing();
  await tx.insert(authOrganizations).values({id:"seed-yodev",name:"YoDev",slug:"yodev-seed"}).onConflictDoNothing();
  await tx.insert(authMembers).values({id:"seed-membership",organizationId:"seed-yodev",userId:"seed-owner",role:"owner"}).onConflictDoNothing();
  await tx.insert(workspaceProfiles).values({id:ids.workspace,organizationId:"seed-yodev",name:"YoDev",slug:"yodev-seed",baseCurrency:"EUR",locale:"fr"}).onConflictDoNothing();
  await tx.insert(providers).values(providerCatalog).onConflictDoNothing();
  await tx.insert(clients).values([{id:ids.internal,workspaceId:ids.workspace,name:"Internal",slug:"internal",description:"YoDev products and internal operations"},{id:ids.parigo,workspaceId:ids.workspace,name:"Parigo",slug:"parigo",description:"Client delivery and infrastructure"},{id:ids.demo,workspaceId:ids.workspace,name:"Demo Client",slug:"demo-client",description:"Safe development demonstration data"}]).onConflictDoNothing();
  await tx.insert(projects).values([{id:ids.spend,workspaceId:ids.workspace,clientId:ids.internal,name:"Spend",slug:"spend",description:"Developer infrastructure spend management"},{id:ids.parigoWeb,workspaceId:ids.workspace,clientId:ids.parigo,name:"Parigo Website",slug:"parigo-website"},{id:ids.jobio,workspaceId:ids.workspace,clientId:ids.internal,name:"Jobio",slug:"jobio"}]).onConflictDoNothing();
  await tx.insert(repositories).values([{workspaceId:ids.workspace,projectId:ids.spend,source:"github",externalId:900001,owner:"yodev",name:"spend",fullName:"yodev/spend",defaultBranch:"main",isPrivate:true,htmlUrl:"https://github.com/example/spend",scanEnabled:false},{workspaceId:ids.workspace,projectId:ids.parigoWeb,source:"github",externalId:900002,owner:"demo",name:"parigo-web",fullName:"demo/parigo-web",defaultBranch:"main",isPrivate:true,htmlUrl:"https://github.com/example/parigo-web",scanEnabled:false}]).onConflictDoNothing();
  const providerRows=await tx.select().from(providers);const p=new Map(providerRows.map((item)=>[item.slug,item.id]));
  await tx.insert(projectIntegrations).values([{workspaceId:ids.workspace,projectId:ids.parigoWeb,providerId:p.get("resend")!,lifecycleStatus:"candidate",reviewStatus:"pending",confidence:95,lastDetectedAt:new Date()},{workspaceId:ids.workspace,projectId:ids.parigoWeb,providerId:p.get("sendgrid")!,lifecycleStatus:"stale",reviewStatus:"confirmed",confidence:90,lastDetectedAt:new Date(Date.now()-24*86400000),staleAt:new Date()},{workspaceId:ids.workspace,projectId:ids.spend,providerId:p.get("vercel")!,lifecycleStatus:"active",reviewStatus:"confirmed",confidence:100,lastDetectedAt:new Date()}]).onConflictDoNothing();
  const [sendgridAccount]=await tx.insert(billingAccounts).values({workspaceId:ids.workspace,providerId:p.get("sendgrid")!,name:"Legacy SendGrid",ownerType:"workspace",status:"active",defaultCurrency:"EUR"}).onConflictDoNothing().returning({id:billingAccounts.id});
  let accountId=sendgridAccount?.id;if(!accountId){const [row]=await tx.select({id:billingAccounts.id}).from(billingAccounts).where(eq(billingAccounts.name,"Legacy SendGrid")).limit(1);accountId=row.id;}
  await tx.insert(billingAccountProjects).values({workspaceId:ids.workspace,billingAccountId:accountId,projectId:ids.parigoWeb,allocationBps:10000}).onConflictDoNothing();
  const [subscription]=await tx.insert(subscriptions).values({workspaceId:ids.workspace,billingAccountId:accountId,name:"SendGrid Essentials",billingModel:"fixed_monthly",amountMinor:1900n,currency:"EUR",billingInterval:"month",status:"active",renewalDate:new Date(Date.now()+12*86400000)}).onConflictDoNothing().returning({id:subscriptions.id});
  if(subscription)await tx.insert(costEntries).values({workspaceId:ids.workspace,billingAccountId:accountId,subscriptionId:subscription.id,amountMinor:1900n,currency:"EUR",periodStart:new Date(new Date().getUTCFullYear(),new Date().getUTCMonth(),1),periodEnd:new Date(new Date().getUTCFullYear(),new Date().getUTCMonth()+1,0),kind:"subscription",source:"manual",description:"Development seed cost"}).onConflictDoNothing();
  await tx.insert(alerts).values([{workspaceId:ids.workspace,type:"POSSIBLE_MIGRATION",severity:"warning",dedupeKey:"seed:migration:sendgrid:resend",providerId:p.get("resend")!,projectId:ids.parigoWeb,title:"Possible migration: SendGrid → Resend",description:"Resend appeared shortly before SendGrid became stale."},{workspaceId:ids.workspace,type:"PAID_PROVIDER_WITHOUT_PROJECT",severity:"critical",dedupeKey:"seed:waste:sendgrid",providerId:p.get("sendgrid")!,billingAccountId:accountId,title:"Potential waste: SendGrid",description:"Recurring cost remains active while no current usage is detected."}]).onConflictDoNothing();
});console.log("Spend development data seeded.");}

main().then(()=>process.exit(0)).catch((error)=>{console.error(error instanceof Error?error.message:"Seed failed");process.exit(1)});
